version: '3'
services:
    weather:
        build: .
        hostname: "superawesomeweather"
        ports:
          - "${HTTP_PORT}:${HTTP_PORT}"
        environment:
            - HTTP_PORT=${HTTP_PORT}
            - OPENWEATHER=${OPENWEATHER}
            - WEATHERSTACK=${WEATHERSTACK}
